AllCops:
  Exclude:
    - bin/**/*
    - db/schema.rb
    - vendor/**/*
  SuggestExtensions: false
  NewCops: enable

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - test/**/*

Metrics/MethodLength:
  Max: 15